routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('student', 'StudentController');
Route::resource('teacher', 'TeacherController');
Route::resource('degree', 'DegreeController');
Route::resource('assignment', 'AssignmentController');

resources/views/createDegree.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Colegio</title>
</head>
<body>
	 <form method="post"" action="{{ route('degree.store') }}">
	    	@csrf
			<div>
		      
		     <div>
		        <label for="Name">Nombre:</label>
		        <input type="text" class="form-control" name="nombre">
		      </div>
		    </div>

		    <div>
				<div>
				    <label>maestros</label>
				    <select class="form-control" name="maestro">
				    	@foreach($maestros as $maestro)
				      		<option value="{{$maestro->id}}">{{ $maestro->nombre }} {{ $maestro->apellido }}</option>
				      	@endforeach
				    </select>
				</div>	
			</div> 

		    <div>
	          <div class="form-group col-md-6">
	            <button type="submit" class="btn btn-primary">Agregar</button>
	          </div>
	        </div>
	</form>
</body>
</html>

resources/views/createStudent.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Colegio</title>
</head>
<body>
	 <form method="post"" action="{{ route('student.store') }}">
	    	@csrf
			<div>
		      
		     <div class="form-group col-md-6">
		        <label for="Name">Nombre:</label>
		        <input type="text" class="form-control" name="nombre">
		      </div>
		    </div>

			<div>
		    	<div class="form-group col-md-6">
		        	<label for="Name">Apellido:</label>
		        	<input type="text" class="form-control" name="apellido">
		      	</div>
		    </div>

		   <!--  <div class="form-group">
		    <label for="exampleFormControlSelect1">Example select</label>
		    <select class="form-control" id="exampleFormControlSelect1">
		      <option>Femenino</option>
		      <option>Masculino</option>
		     
		    </select>
		  </div> -->

		    <div>
		    	<div class="form-group col-md-6">
		        	<label for="Name">Genero:</label>
		        	<input type="text" class="form-control" name="genero">
		      	</div>
		    </div>

		    <div>
		    	<div class="form-group col-md-6">
		        	<label for="Name">Fecha Nacimiento:</label>
		        	<input type="text" class="form-control" name="fecha_nacimiento">
		      	</div>
		    </div>

		    <div>
	          <div class="form-group col-md-6">
	            <button type="submit" class="btn btn-primary">Agregar</button>
	          </div>
	        </div>
	</form>
</body>
</html>

resources/views/createStudentDegree.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Colegio</title>
</head>
<body>
	 <form method="post"" action="{{ route('assignment.store') }}">
	    	@csrf
			<div>
		      
		     <div>
		        <label for="Name">Seccion:</label>
		        <input type="text" class="form-control" name="seccion">
		      </div>
		    </div>

		    <div>
				<div>
				    <label>Alumnos</label>
				    <select class="form-control" name="estudiante">
				    	@foreach($estudiantes as $estudiante)
				      		<option value="{{$estudiante->id}}">{{ $estudiante->nombre }} {{ $estudiante->apellido }}</option>
				      	@endforeach
				    </select>
				</div>	
			</div> 

			<div>
				<div>
				    <label>Grado</label>
				    <select class="form-control" name="grado">
				    	@foreach($grados as $grado)
				      		<option value="{{$grado->id}}">{{ $grado->nombre }} {{ $grado->apellido }}</option>
				      	@endforeach
				    </select>
				</div>	
			</div> 

		    <div>
	          <div class="form-group col-md-6">
	            <button type="submit" class="btn btn-primary">Agregar</button>
	          </div>
	        </div>
	</form>
</body>
</html>

resources/views/createTeacher.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Colegio</title>
</head>
<body>
	 <form method="post"" action="{{ route('teacher.store') }}">
	    	@csrf
			<div>
		      
		     <div class="form-group col-md-6">
		        <label for="Name">Nombre:</label>
		        <input type="text" class="form-control" name="nombre">
		      </div>
		    </div>

			<div>
		    	<div class="form-group col-md-6">
		        	<label for="Name">Apellido:</label>
		        	<input type="text" class="form-control" name="apellido">
		      	</div>
		    </div>

		    <div>
		    	<div class="form-group col-md-6">
		        	<label for="Name">Genero:</label>
		        	<input type="text" class="form-control" name="genero">
		      	</div>
		    </div>

		    

		    <div>
	          <div class="form-group col-md-6">
	            <button type="submit" class="btn btn-primary">Agregar</button>
	          </div>
	        </div>
	</form>
</body>
</html>

resources/views/editAssignment.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Colegio</title>
</head>
<body>
	 <form method="post"" action="{{ route('assignment.update', $alumnosg->id) }}">
	    	@csrf

	    	<input name="_method" type="hidden" value="PUT">
			<div>
		      
		     <div>
		        <label for="Name">Seccion:</label>
		        <input type="text" class="form-control" name="seccion">
		      </div>
		    </div>

		    <div>
				<div>
				    <label>Alumnos</label>
				    <select class="form-control" name="estudiante">
				    	@foreach($estudiantes as $estudiante)
				      		<option value="{{$estudiante->id}}">{{ $estudiante->nombre }} {{ $estudiante->apellido }}</option>
				      	@endforeach
				    </select>
				</div>	
			</div> 

			<div>
				<div>
				    <label>Grado</label>
				    <select class="form-control" name="grado">
				    	@foreach($grados as $grado)
				      		<option value="{{$grado->id}}">{{ $grado->nombre }} {{ $grado->apellido }}</option>
				      	@endforeach
				    </select>
				</div>	
			</div> 

		    <div>
	          <div class="form-group col-md-6">
	            <button type="submit" class="btn btn-primary">Agregar</button>
	          </div>
	        </div>
	</form>
</body>
</html>

resources/views/editDegree.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Colegio</title>
</head>
<body>
	 <form method="post"" action="{{ route('degree.update', $degree->id) }}">
	    	@csrf
	    	<input name="_method" type="hidden" value="PUT">
			<div>
		      
		     <div class="form-group col-md-6">
		        <label for="Name">Nombre:</label>
		        <input type="text" class="form-control" name="nombre" value="{{$degree->nombre}}">
		      </div>
		    </div>

		     <div>
				<div>
				    <label>maestros</label>
				   
				    <select class="form-control" name="profesor_id">

				    	
						<option value="{{$degree->profesor_id}}">{{$nombre_maestro->nombre}} {{$nombre_maestro->apellido}}</option>

				    	@foreach($maestros as $maestro)
				      		<option value="{{$maestro->id}}">{{ $maestro->nombre }} {{ $maestro->apellido }}</option>

				      	@endforeach
				    </select>
				</div>	
			</div> 

		    <div>
	          <div>
	            <button type="submit" class="btn btn-primary">Editar</button>
	          </div>
	        </div>
	</form>
</body>
</html>

resources/views/editStudent.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Colegio</title>
</head>
<body>
	 <form method="post"" action="{{ route('student.update', $student->id) }}">
	    	@csrf
	    	<input name="_method" type="hidden" value="PUT">
			<div>
		      
		     <div class="form-group col-md-6">
		        <label for="Name">Nombre:</label>
		        <input type="text" class="form-control" name="nombre" value="{{$student->nombre}}">
		      </div>
		    </div>

			<div>
		    	<div class="form-group col-md-6">
		        	<label for="Name">Apellido:</label>
		        	<input type="text" class="form-control" name="apellido" value="{{$student->apellido}}">
		      	</div>
		    </div>

		    <div>
		    	<div class="form-group col-md-6">
		        	<label for="Name">Genero:</label>
		        	<input type="text" class="form-control" name="genero" value="{{$student->genero}}">
		      	</div>
		    </div>

		    <div>
		    	<div class="form-group col-md-6">
		        	<label for="Name">Fecha Nacimiento:</label>
		        	<input type="text" class="form-control" name="fecha_nacimiento" value="{{$student->fecha_nacimiento}}">
		      	</div>
		    </div>

		    <div>
	          <div class="form-group col-md-6">
	            <button type="submit" class="btn btn-primary">Editar</button>
	          </div>
	        </div>
	</form>
</body>
</html>

resources/views/editTeacher.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Colegio</title>
</head>
<body>
	 <form method="post"" action="{{ route('teacher.update', $teacher->id) }}">
	    	@csrf
	    	<input name="_method" type="hidden" value="PUT">
			<div>
		      
		     <div class="form-group col-md-6">
		        <label for="Name">Nombre:</label>
		        <input type="text" class="form-control" name="nombre" value="{{$teacher->nombre}}">
		      </div>
		    </div>

			<div>
		    	<div class="form-group col-md-6">
		        	<label for="Name">Apellido:</label>
		        	<input type="text" class="form-control" name="apellido" value="{{$teacher->apellido}}">
		      	</div>
		    </div>

		    <div>
		    	<div class="form-group col-md-6">
		        	<label for="Name">Genero:</label>
		        	<input type="text" class="form-control" name="genero" value="{{$teacher->genero}}">
		      	</div>
		    </div>

		    <div>
	          <div class="form-group col-md-6">
	            <button type="submit" class="btn btn-primary">Editar</button>
	          </div>
	        </div>
	</form>
</body>
</html>

resources/views/indexAlumnosG.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Colegio</title>
</head>
<body>

	<a href="http://colegio.test/">Inicio</a>
	<table>
	  <thead>
	    <tr>
	      <th>Alumno</th>
	      <th>Grado</th>
	      <th>Seccion</th>
	    </tr>
	  </thead>
	  <tbody>
	  	@foreach($alumnosg as $al)
	    <tr>
	     
	      <td>{{$al->alumno_id}}</td>
	      <td>{{$al->grado_id}}</td>
	      <td>{{$al->seccion}} </td>
	     
	      <td><a href=" {{ route('assignment.edit', $al->id) }} ">Editar</a></td>
	     
	      <td>	
				<form method="POST" action="{{ route('assignment.destroy', $al->id) }}">
					@csrf
					{!! method_field('DELETE') !!}
					<button type="submit">Eliminar</button>
				</form>
	      	</td>



	    </tr>
	    @endforeach	
	  </tbody>
</table>

<a href=" {{ route('assignment.create') }} ">Crear Asignaciòn</a>

	
</body>
</html>

resources/views/indexGrado.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Colegio</title>
</head>
<body>

	<a href="http://colegio.test/">Inicio</a>
	<table>
	  <thead>
	    <tr>
	      <th>Nombre</th>
	    </tr>
	  </thead>
	  <tbody>
	  	@foreach($grados as $grado)
	    <tr>
	      <td>{{$grado->nombre}} </td>
	     
	      <td><a href=" {{ route('degree.edit', $grado->id) }} ">Editar</a></td>
	     
	      <td>	
				<form method="POST" action="{{ route('degree.destroy', $grado->id) }}">
					@csrf
					{!! method_field('DELETE') !!}
					<button type="submit">Eliminar</button>
				</form>
	      	</td>



	    </tr>
	    @endforeach	
	  </tbody>
</table>

<a href=" {{ route('degree.create') }} ">Crear Grado</a>

	
</body>
</html>

resources/views/indexMaestro.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Colegio</title>
</head>
<body>

	<a href="http://colegio.test/">Inicio</a>
	<table>
	  <thead>
	    <tr>
	      <th>Nombre</th>
	      <th>Genero</th>
	      <th>actualizar</th>
	      <th>eliminar</th>
	    </tr>
	  </thead>
	  <tbody>
	  	@foreach($maestros as $maestro)
	    <tr>
	      
	      <td>{{$maestro->nombre}} {{$maestro->apellido }}</td>
	      <td>{{$maestro->genero}} </td>
	     
	      <td><a href=" {{ route('teacher.edit', $maestro->id) }} ">Editar</a></td>
	     
	      <td>	
				<form method="POST" action="{{ route('teacher.destroy', $maestro->id) }}">
					@csrf
					{!! method_field('DELETE') !!}
					<button type="submit">Eliminar</button>
				</form>
	      	</td>



	    </tr>
	    @endforeach	
	  </tbody>
</table>

<a href=" {{ route('teacher.create') }} ">Crear Maestro</a>

	
</body>
</html>

resources/views/indexStudents.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Colegio</title>
</head>
<body>

	<a href="http://colegio.test/">Inicio</a>
	<table>
	  <thead>
	    <tr>
	      <th>Nombre</th>
	      <th>Genero</th>
	      <th>Fecha Nacimiento</th>
	      <th>actualizar</th>
	      <th>eliminar</th>
	    </tr>
	  </thead>
	  <tbody>
	  	@foreach($estudiantes as $est)
	    <tr>
	      
	      <td>{{$est->nombre}} {{$est->apellido }}</td>
	      <td>{{$est->genero}} </td>
	      <td>{{$est->fecha_nacimiento}}</td>
	      <td><a href=" {{ route('student.edit', $est->id) }} ">Editar</a></td>
	     
	      <td>	
				<form method="POST" action="{{ route('student.destroy', $est->id) }}">
					@csrf
					{!! method_field('DELETE') !!}
					<button type="submit">Eliminar</button>
				</form>
	      	</td>



	    </tr>
	    @endforeach	
	  </tbody>
</table>


<a href=" {{ route('teacher.create') }} ">Crear Estudiante</a>
	
</body>
</html>